%macro undersized(data=,ID=,size=,tot_size=,undersized=,pop=,neighbor=,shape=,nneigh=3,order=);
proc sort data=&data;by &tot_size;run;
proc iml;
use &data;
read all var{&id &undersized};
use &neighbor;
read all var{&id &id.1} into NEIGH;
n=nrow(&undersized);
&id.2=&id||j(n,1,'0');
check3=0;
print "Iteration 1";
do i=1 to n;
if &undersized[i]=1 then do;
j=1;
viz=NEIGH[loc(NEIGH[,1]=&id[i]),2];
viz=viz[j,];
*print viz;
check=&id.2[loc(&id=viz),2];
if i>1 then check3=ncol(loc(&id.2[1:i-1,1]=&id[i]));
if check='0' & check3=0 then do;&id.2[i,1]=viz;&id.2[i,2]='1';
print (&id[i]) "joined with" viz[label=''];
end;
*check=ncol(loc(CD_MUN2=viz));
*if check>0 then CD_MUN2[i]=viz;
end;
end;
create _under_ from &id.2[colname={"&id.2" "join"}];
append from &id.2;
quit;
proc sql noprint;select mean(input(join,1.)) into:mjoin from _under_;quit;
%put &mjoin;

data &data.j;merge &data _under_;
if &id ne &id.2 then &id.c=trim(left(&id))||","||trim(left(&id.2));
else &id.c=&id;
&id.f=&id.c;
run;
/*proc freq data=&data.j noprint;
tables &id.2 /out=&data.2(rename=(count=&tot_size) drop=percent);
weight &tot_size;
run;*/
proc means data=&data.j nway noprint;
class &id.2;
var &tot_size;
output out=&data.2(drop=_type_ _freq_) sum=&tot_size;
run;
/*proc freq data=&data.j noprint;
tables &id.2 /out=&data.2p(rename=(count=&pop) drop=percent);
weight &pop;
run;*/
proc means data=&data.j nway noprint;
class &id.2;
var &pop;
output out=&data.2p(drop=_type_ _freq_) sum=&pop;
run;
data &data.2;merge &data.2 &data.2p;
_size_=&size;
if &tot_size<_size_ then &undersized=1;else &undersized=0;
run;
proc sql noprint;
select count(*) into:n_under from &data.2
where &undersized=1;
quit;
%put &n_under;

%let k=1;
%do %while(&n_under>0 and &k<=30);
proc sort data=&data.2;by &order &tot_size;run;
proc iml;
use &data.2;
read all var{&id.2 &undersized};
use &neighbor;
read all var{&id &id.1} into NEIGH;
n=nrow(&undersized);
&id.2=&id.2||j(n,1,'0');
check3=0;
print "Iteration %eval(&k+1)";
do i=1 to n;
if &undersized[i]=1 then do;
j=1;
g=10;
check=0;
do while(check=0 & j<=g);
viz=NEIGH[loc(NEIGH[,1]=&id.2[i,1]),2];
g=nrow(viz);
viz=viz[j,];
*print i viz;
check=ncol(loc(&id.2[,1]=viz));
if check>0 then do;
check2=&id.2[loc(&id.2[,1]=viz),2];
if i>1 then check3=ncol(loc(&id.2[1:i-1,1]=&id.2[i,1]));
if check2='0' & check3=0 then do;value_old=&id.2[i,1];&id.2[i,1]=viz;&id.2[i,2]='1';
print value_old[label=''] "joined with" viz[label=''];
end;
end;
j=j+1;
end;
end;
end;
create _under_ from &id.2[colname={"&id.2" "join"}];
append from &id.2;
quit;
proc sql noprint;select mean(input(join,1.)) into:mjoin from _under_;quit;
%put &mjoin;

%if &mjoin=0 and &n_under>&nneigh %then %do;
proc print data=&data.2 noobs;
var &id.2 &tot_size _size_ &undersized;
where &undersized=1;
run;

%put WARNING: **** Using Neighbors of Second Order ****;
proc sort data=&data.2;by &order &tot_size;run;
proc iml;
use &data.2;
read all var{&id.2 &undersized};
use &neighbor;
read all var{&id &id.1} into NEIGH;
n=nrow(&undersized);
&id.2=&id.2||j(n,1,'0');
check3=0;
print "Using Neighbors of Second Order";
do i=1 to n;
if &undersized[i]=1 then do;
j=1;
g=10;
check=0;
do while(check=0 & j<=g);
viz=NEIGH[loc(NEIGH[,1]=&id.2[i,1]),2];
g=nrow(viz);
viz=viz[j,];
l=1;
h=10;
check2='0';
do while(check=0 & l<=h);
viz2=NEIGH[loc(NEIGH[,1]=viz),2];
h=nrow(viz2);
viz2=viz2[l,];
*print i l h;
check=ncol(loc(&id.2[,1]=viz2));
if check>0 then do;
check2=&id.2[loc(&id.2[,1]=viz2),2];
if i>1 then check3=ncol(loc(&id.2[1:i-1,1]=&id.2[i,1]));
if check2='0' & check3=0 & &id.2[i,1]^=viz2 then do;value_old=&id.2[i,1];&id.2[i,1]=viz2;&id.2[i,2]='1';
print value_old[label=''] "joined with" viz2[label=''];
end;
end;
l=l+1;
end;
j=j+1;
end;
end;
end;
create _under_ from &id.2[colname={"&id.2" "join"}];
append from &id.2;
quit;
proc sql noprint;select mean(input(join,1.)) into:mjoin from _under_;quit;
%put &mjoin;

%end;

%if &mjoin=0 and &n_under<=&nneigh %then %do;
proc print data=&data.2 noobs;
var &id.2 &tot_size _size_ &undersized;
where &undersized=1;
run;
%put WARNING: **** Using Neighbors of Third Order ****;

proc sort data=&neighbor out=&neighbor.2;by &id descending &tot_size;run;
proc iml;
use &data.2;
read all var{&id.2 &undersized};
use &neighbor.2;
read all var{&id &id.1} into NEIGH;
n=nrow(&undersized);
&id.2=&id.2||j(n,1,'0');
check3=0;
print "Using Neighbors of Second Order";
do i=1 to n;
if &undersized[i]=1 then do;
j=1;
g=10;
check=0;
do while(check=0 & j<=g);
viz=NEIGH[loc(NEIGH[,1]=&id.2[i,1]),2];
g=nrow(viz);
viz=viz[j,];
l=1;
h=10;
check2='0';
do while(check=0 & l<=h);
viz2=NEIGH[loc(NEIGH[,1]=viz),2];
h=nrow(viz2);
viz2=viz2[l,];
*print i l h;
check=ncol(loc(&id.2[,1]=viz2));
if check>0 then do;
check2=&id.2[loc(&id.2[,1]=viz2),2];
if i>1 then check3=ncol(loc(&id.2[1:i-1,1]=&id.2[i,1]));
if check2='0' & check3=0 & &id.2[i,1]^=viz2 then do;value_old=&id.2[i,1];&id.2[i,1]=viz2;&id.2[i,2]='1';
print value_old[label=''] "joined with" viz2[label=''];
end;
end;
l=l+1;
end;
j=j+1;
end;
end;
end;
create _under_ from &id.2[colname={"&id.2" "join"}];
append from &id.2;
quit;
proc sql noprint;select mean(input(join,1.)) into:mjoin from _under_;quit;
%put &mjoin;

%end;

data &data.2;merge &data.2(keep=&id.2 &tot_size &pop rename=&id.2=&id) _under_;
if &id ne &id.2 then &id.c%eval(1+&k)=trim(left(&id))||","||trim(left(&id.2));
else &id.c%eval(1+&k)=&id;
run;
proc sort data=&data.2;by &id;run;
proc sort data=&data.j;by &id.%eval(1+&k);run;
data &data.j;merge &data.j &data.2(keep=&id &id.2 &id.c%eval(1+&k)
rename=(&id.2=&id.%eval(2+&k) &id=&id.%eval(1+&k)));
by &id.%eval(1+&k);
&id.f=CATX(",",&id.f,&id.c%eval(1+&k));
run;
/*proc freq data=&data.2 noprint;
tables &id.2 /out=&data.2p(rename=(count=&pop) drop=percent);
weight &pop;
run;*/
proc means data=&data.2 nway noprint;
class &id.2;
var &pop;
output out=&data.2p(drop=_type_ _freq_) sum=&pop;
run;
/*proc freq data=&data.2 noprint;
tables &id.2 /out=&data.2(rename=(count=&tot_size) drop=percent);
weight &tot_size;
run;*/
proc means data=&data.2 nway noprint;
class &id.2;
var &tot_size;
output out=&data.2(drop=_type_ _freq_) sum=&tot_size;
run;
data &data.2;merge &data.2 &data.2p;
_size_=&size;
if &tot_size<_size_ then &undersized=1;else &undersized=0;
run;
proc sql noprint;
select count(*) into:n_under from &data.2
where &undersized=1;
quit;
%put &n_under;
%let k=%eval(&k+1);
%end;

proc sql;select sum(&pop) as M0 from &data.2;quit;
%put &M0;
data &data.j;set &data.j;
*&id.f=CATX(",", of &id.c:);
joins=length(&id.f)-length(compress(&id.f,','))+1;
run;
%macro j;
proc sql noprint;select max(joins) into:max from &data.j;quit;
data &data.j;set &data.j;
%do i=1 %to &max;
cod&i=scan(&id.f,&i,',');
%end;
*if joins<&max then &id%left(%eval(&max-1))=scan(&id.f,joins,',');
run;
%mend j;
%j;
proc sort data=&data.j;by &id;run;
proc transpose data=&data.j out=&data.jt(drop=_name_);
by &id;var cod:;
run;
data &data.jt;set &data.jt;if col1 ne '';run;
data &data.jt;merge &data.jt &data.j(keep=&id &id%eval(1+&k));
by &id;
if &id%eval(1+&k) ne '';
run;
proc sort data=&data.jt nodupkey;by &id%eval(1+&k) col1;run;

proc freq data=&data.jt noprint;
tables &id%eval(1+&k) /out=_freq_mult_(drop=percent rename=count=freq);
run;
data &data.jt2;merge &data.jt _freq_mult_;by &id%eval(1+&k);
if freq>1;
run;
proc sql noprint;
select count(DISTINCT &id%eval(1+&k)) into :cnt_cod from &data.jt2;
select DISTINCT &id%eval(1+&k) into :cod1 - :cod%left(&cnt_cod)
from &data.jt2;
quit;
%put &cnt_cod &cod1;

%if &shape ne %then %do;
%macro jt;
data &shape.2;set &shape.;run;
proc sql;drop table _xj_;run;
%do i=1 %to &cnt_cod;
proc sql noprint;
select col1 into:group separated by "' '" from &data.jt
where &id%eval(1+&k)="&&cod&i";
quit;
/*%put &group;*/
data _x_;length var $5000.;var="'"||"&group"||"'";value="&&cod&i";
call symput("group&i",var);run;
proc append base=_xj_ data=_x_ force;run;
%put &&cod&i &&group&i;
%end;
proc sql noprint;select max(length(var)) into:lv from _xj_;quit;
%put &lv;
data _xj_;length var $&lv..;set _xj_;run;
data &shape.2;set &shape.2;
%do i=1 %to &cnt_cod;
if &id in (&&group&i) then &id.2="&&cod&i";
%end;
if &id.2='' then &id.2=&id;
run;
%mend jt;
%jt;

goptions reset=all reset=global;
proc gmap data=&data.2 map=&shape.2 all;
id &id.2;
choro &id.2;
run;
quit;
proc gmap data=&data.2 map=&shape.2 all;
id &id.2;
choro &id.2 /nolegend;
run;
quit;
%end;

%mend undersized;



%macro oversized(data=,size=,tot_size=,oversized=,strata=,M0=);
data &data;set &data;
M0=&M0;
a=&size;
if &tot_size>M0/a then &oversized.1=1;else &oversized.1=2;
weight_PSU=M0/(&size*&tot_size);
run;

%let k=2;
%let prob1=1;
%do %while(&prob1>0);
proc means data=&data noprint nway;
var &tot_size;
class &strata &oversized%eval(&k-1);
output out=_sum_pop_str_(drop=_type_ rename=_freq_=_freq_str) sum=_pop_str_;
run;

%if &strata= %then %do;
proc sql noprint;
select _pop_str_ into:M02 from _sum_pop_str_
where &oversized%eval(&k-1)=2;
select _freq_str into:Str1 from _sum_pop_str_
where &oversized%eval(&k-1)=1;
quit;
%put &M02 &Str1;

data &data;set &data;
if &oversized%eval(&k-1)=1 then weight_PSU=1;
if &oversized%eval(&k-1)=2 then weight_PSU=&M02/((&size-&Str1)*&tot_size);
if &tot_size>(&M02/(&size-&Str1)) then &oversized.&k=1;else &oversized.&k=2;
if &oversized%eval(&k-1)=1 then &oversized.&k=1;
if &oversized.&k=1 then _ah_=&Str1;
if &oversized.&k=2 then _ah_=&size-&Str1;
run;
%end;

%else %do;
data _sum_pop_str1_;set _sum_pop_str_(where=(&oversized%eval(&k-1)=1) 
rename=_freq_str=_freq_str1 drop=_pop_str_);
run;
%if &k=2 %then %do;
proc sort data=&data;by &strata &oversized%eval(&k-1);run;
%end;
%else %do;
proc sort data=&data(drop=_freq_str1 _ah_ _pop_str_);by &strata &oversized%eval(&k-1);run;
%end;
data &data;merge &data _sum_pop_str1_;
by &strata;
if _freq_str1=. then _freq_str1=0;
run;
data &data;merge &data _sum_pop_str_;
by &strata &oversized%eval(&k-1);
if &oversized%eval(&k-1)=1 then weight_PSU=1;
if &oversized%eval(&k-1)=2 then weight_PSU=_pop_str_/((&size-_freq_str1)*&tot_size);
if &tot_size>(_pop_str_/(&size-_freq_str1)) then &oversized.&k=1;else &oversized.&k=2;
if &oversized%eval(&k-1)=1 then &oversized.&k=1;
if &oversized.&k=1 then _ah_=_freq_str1;
if &oversized.&k=2 then _ah_=&size-_freq_str1;
run;
%end;


proc sql noprint;
select count(*) into:prob1 from &data
where weight_PSU<1;
quit;
%put &prob1;
%let k=%eval(&k+1);
%end;
data &data;set &data;
&oversized=&oversized%eval(&k-1);
run;

%mend oversized;
